### PR TITLE
bump few dependencies

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by mgeisler** [comment]
Hey @ignatenkobrain, thanks for the PR. As you probably saw, it failed in Travis since it tests again Rust 1.15. You write

> We don't need to force such old compiler as 1.15.x nowadays.

However, I recently tried to add this create to the MIO project. They still support Rust 1.14, so my PR failed: https://github.com/carllerche/mio/pull/754

I am just a hobby Rust programmer and I don't have a super good sense of how far back people normally support old versions of the compiler. I see "stable minus two releases" mentioned here and there, but it seems there are projects out there with bigger ambitions.

If there's no burning need for it, then I would prefer to keep support with old versions.

**Comment by ignatenkobrain** [comment]
Problematic part is that I would need to keep this patching in Fedora when packaging version-sync which is not really nice.

**Comment by mgeisler** [comment]
Okay, I see... are the versions you picked the ones used in Fedora at the moment, or are they just the latest version of each dependency? Do you know what the new minimum version of Rust will be with the bumped dependencies?

I would like to make it as easy as possible for people to use version-sync. Using the old dependencies allows it to compile on ancient versions of Rust, but perhaps the old dependencies will also turn some people away from the library?

**Comment by ignatenkobrain** [comment]
> are the versions you picked the ones used in Fedora at the moment, or are they just the latest version of each dependency?

Both.

> Do you know what the new minimum version of Rust will be with the bumped dependencies?

Not really, but should not be hard to check.

> but perhaps the old dependencies will also turn some people away from the library?

As a developer I would prefer to stick to latest versions except if it's really needed to use old ones.

**Comment by mgeisler** [comment]
Okay, I say we bump the minimum supported Rust version to 1.17 -- please see #31. When that is in, we can merge this PR as well.

**Pull request merged**
