### PR TITLE
bump regex and lazy_static to the latest version

### PR DESCRIPTION
**Pull request by ubnt-intrepid**

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi @ubnt-intrepid, thanks for the PR. I'm happy to merge this since 1.27.2 was released about six months ago now.

Can I get you to reorder the two commits? Right now the first commit changes the versions, and the second commit updates the Travis configuration so that the build is green. That means that the build fails on the first commit. If you reorder them, then the build is green on all commits.

**Comment by ubnt-intrepid** [comment]
@mgeisler Ok, I've just reorder the commits and restart the CI jobs.

**Comment by emabee** [comment]
Thanks for going forward with this :-)
I just wanted to provide the same PR since I'm currently blocked by "error: failed to select a version for `lazy_static`."

**Comment by mgeisler** [comment]
Thanks @ubnt-intrepid, it's merged now!

And thanks @emabee, I hadn't realized that the old version was causing trouble like that... I'll release a new version then.

**Comment by mgeisler** [comment]
@emabee, I've just released version 0.7.0 with all dependencies bumped to their latest version.

**Comment by emabee** [comment]
Thanks!

**Comment by ubnt-intrepid** [comment]
Thanks for your quick work!

**Pull request merged**
